# Numpy

- It is used for creating N-Dimensional array.
- Ability to quickly broadcasts functions.
- Built-in linear algebra, statistical distributions, trignometric, and random number capabilities.

In [1]:
import numpy as np

In [3]:
# Creating an array from a list
mylist = [1, 2, 3, 4, 5]
print(type(mylist))
print(mylist)

<class 'list'>
[1, 2, 3, 4, 5]


In [4]:
myarr = np.array(mylist)
print(type(myarr)) 
print(myarr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [6]:
matrix_arr = np.array(matrix)
print(matrix_arr)
print(type(matrix_arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [7]:
# np.arange(start, stop, step)
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# np.linspace(start, stop, num)
# gives evenly spaced numbers over a specified interval
np.linspace(0, 10, 3)  # 3 numbers between 0 and 10

array([ 0.,  5., 10.])

In [16]:
# Identity Matrix
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Generate random numbers
np.random.rand(5)  # 1D array of 5 random numbers between

array([0.7109201 , 0.23847328, 0.49483652, 0.8792011 , 0.3008031 ])

In [18]:
np.random.rand(1)

array([0.74222143])

In [20]:
np.random.rand(3,4) # 3 rows and 4 columns

array([[0.49978827, 0.8244335 , 0.545506  , 0.99480451],
       [0.80351566, 0.88969434, 0.36158635, 0.41137347],
       [0.16856702, 0.94033945, 0.34609785, 0.77161551]])

In [21]:
# np.random.randint(start, stop (not inclusive), size) Gives integers
np.random.randint(0, 101, 5)

array([83, 54, 32, 73, 91])

In [22]:
np.random.randint(0, 101, (3,4))

array([[94, 85, 81, 43],
       [36, 95, 11, 46],
       [87, 10, 95, 51]])

In [23]:
# To get the same random numbers each time
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
# reshaping arrays
arr = np.arange(0, 25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [26]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
# Getting highest maximum and minimum values, and their positions
arr = np.random.randint(0, 101, 10)
print(arr)

[ 1 87 29 37  1 63 59 20 32 75]


In [31]:
print("Max:", arr.max())
print("Min:", arr.min())
print("Argmax (index of max):", arr.argmax())
print("Argmin (index of min):", arr.argmin())

Max: 87
Min: 1
Argmax (index of max): 1
Argmin (index of min): 0
